version: '3'
services:
  centos:
    build: .
    privileged: true
    storage_opt:
     size: "20G"
    ports:
     - "5000:5000"
     - "5901:5901"
     - "6901:6901"
     - "3000:3000"
     - "80:80"
     - "8080:8080"
    volumes:
     - "mywork:/headless/Desktop/work"
     - "myatom:/headless/.atom"
     - "mywww:/var/www"
     - "myssh:/headless/.ssh"
     - "mydocker:/var/lib/docker"
     - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
     - "VNC_RESOLUTION=1600x900"
     - "VNC_COL_DEPTH=24"
     - "VNC_PW=pass123"
    cap_add:
     - SYS_ADMIN
     - DAC_READ_SEARCH
